version: "3.9"

services:
  api:
    build: .
    container_name: fastapi_app
    ports:
      - "8000:8000"
    depends_on:
      - db
    restart: always
    environment:
      # 🔹 這裡會覆蓋 .env 裡的設定，讓容器內部連到 db 服務
      - DATABASE_URL=postgresql://user:password@db:5432/mydb
      - SECRET_KEY=yoursecretkey_put_here
      - ALGORITHM=HS256

  db:
    image: postgres:15
    container_name: postgres_db
    restart: always
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: mydb
    ports:
      - "5432:5432"
    volumes:
    - postgres_data:/var/lib/postgresql/data
volumes:
  postgres_data: