name: Deploy to Amazon EC2

on:
  push:
    branches: [ "main" ]  # 當程式碼推送到 main 分支時觸發

jobs:
  deploy:
    runs-on: ubuntu-latest

    # ... 前面省略 ...
    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Deploy to EC2 via SSH
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.EC2_HOST }}
        username: ${{ secrets.EC2_USERNAME }}
        key: ${{ secrets.EC2_SSH_KEY }}
        script: |
          cd ~/fastapi-jwt-task-api
          git fetch --all
          git reset --hard origin/main
          
          printf "DATABASE_URL=%s\n" "${{ secrets.DATABASE_URL }}" > .env
          printf "SECRET_KEY=%s\n" "${{ secrets.SECRET_KEY }}" >> .env
          printf "ALGORITHM=HS256\n" >> .env
          printf "ACCESS_TOKEN_EXPIRE_MINUTES=30\n" >> .env

          sudo /usr/local/bin/docker-compose up --build -d
          docker image prune -f